=pod

=head1 PostgreSQL Mac Preferences

=begin html

<br />
<img src="postgresql-mac-preferences/raw/master/PostgreSQL/elephant.png" />
<img src="postgresql-mac-preferences/raw/master/PostgreSQL/logo.png" />

=end html

=head2 Overview

This project provides a Mac OS X System Preferences pane for the PostgreSQL Database Server.

=head3 Welcome Screen

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_welcome.png" />

=end html

=head3 Start and Stop PostgreSQL

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_startstop.png" />

=end html

=head3 Modify Settings

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_settings.png" />

=end html

=head2 Install Instructions

Download the latest release version L<here|https://github.com/downloads/mckenfra/postgresql-mac-preferences/PostgreSQL.prefPane-v1.0.zip">

Once downloaded, unzip it and then either double-click the C<PostgreSQL.prefPane> file, or drag it to System Preferences to install it.

When installing, you will be asked if you want to install it for this user only, or for all users. You can choose this user only, but either option is fine.

=end html

=head2 Uninstall Instructions

Right-click on the PostgreSQL icon in System Preferences, and click "Remove".

Also, delete the following files if they exist:

=over 4

=item

C</Library/LaunchAgents/com.hkwebentrepreneurs.postgresql.plist*>

=item

C<~/Library/LaunchAgents/com.hkwebentrepreneurs.postgresql.plist*>

=back

=head2 Version History

=over

=item *

v1.0 - 29-Dec 2011 - Initial release 

=back

=head2 Contact

Please email L<mailto:mail@hkwebentrepreneurs.com>

Or visit our website at L<http://www.hkwebentrepreneurs.com>

=cut