=pod

=head1 PostgreSQL Mac Preferences

=over 4

=item * L<|/"Overview">

=item * L<|/"Install Instructions">

=item * L<|/"Uninstall Instructions">
    
=item * L<|/"FAQ">

=item * L<|/"Version History">
        
=item * L<|/"Contact">

C<~/Library/LaunchAgents/com.hkwebentrepreneurs.postgresql.plist*>
    
=back

=begin html

<br />
<img src="postgresql-mac-preferences/raw/master/PostgreSQL/elephant.png" />
<img src="postgresql-mac-preferences/raw/master/PostgreSQL/logo.png" />

=end html

=head2 Overview

=begin html

A Mac OS X System Preferences pane for controlling the PostgreSQL Database Server, offering the following features:

=over 4

=item *

Compatible with all PostgreSQL installations

=item *

Start and stop PostgreSQL Server at the click of a button

=item *

Set PostgreSQL to start automatically on computer bootup

=item *

Easily change PostgreSQL settings in the GUI

=back

This tool was inspired by the excellent work of <a href="http://johntwang.com/blog/2011/04/03/PostgreSQL-Preference-Pane/">John T Wang</a>

=end html

=head3 Welcome Screen

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_welcome.png" />

=end html

=head3 Start and Stop PostgreSQL

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_startstop.png" />

=end html

=head3 Modify Settings

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_settings.png" />

=end html

=head2 Install Instructions

=begin html

Download the latest release version <a href="https://github.com/downloads/mckenfra/postgresql-mac-preferences/PostgreSQL.prefPane-v1.0.zip">here</a>

=end html

Once downloaded, unzip it and then either double-click the C<PostgreSQL.prefPane> file, or drag it to System Preferences to install it.

When installing, you will be asked if you want to install it for this user only, or for all users. Choose this user only (either option is fine however).

=begin html

<img src="postgresql-mac-preferences/raw/master/PostgreSQL/screenshot_install.png" />

=end html

=head2 Uninstall Instructions

Right-click on the PostgreSQL icon in System Preferences, and click "Remove".

Also, delete the following files if they exist:

=over 4

=item * C</Library/LaunchAgents/com.hkwebentrepreneurs.postgresql.plist*>

=item * C<~/Library/LaunchAgents/com.hkwebentrepreneurs.postgresql.plist*>

=back

=head2 FAQ

=over 4

=item * Can I run multiple instances of PostgreSQL on the same machine? 

=item * No, at present the PostgreSQL Preferences only permit one running PostgreSQL instance at a time. The PostgreSQL Preferences will attempt to stop all other running PostgreSQL instances, when the user clicks the Start button to startup PostgreSQL.
    
=back    
    
=head2 Version History

=over 4

=item * v1.0 - 29-Dec 2011 - Initial release 

=back

=head2 Contact

=begin html
    
Please email any feedback to <a href="mailto:email@hkwebentrepreneurs.com">email@hkwebentrepreneurs.com</a>

=end html

Or visit our website at L<http://www.hkwebentrepreneurs.com>

=cut